# EDA {#EDA}

Carguemos las librerias

```{r libreria, message= FALSE, warning=FALSE}
library(tidyverse)
library(Amelia)
library(dplyr)
library(moments)
library(ggplot2)
library(patchwork)
library(readxl)
library(effsize)
library(openintro)
library(nortest)
library(car)
library(coin)
library(BSDA)
library(rstatix)
```

Conjunto de datos
```{r data}
data_cancer <- read.csv("Data/cancer_reg.csv")

data_household <- read.csv("Data/avg-household-size.csv")

```

Muestrame las 5 primeras filas

```{r filas}
head(data_cancer, n= 5)
```

La estructura de los datos

```{r estructura}
str(data_cancer)
```


Veamos si hay datos faltantes

```{r faltante}
data_cancer %>% 
  summarise(across(everything(), ~sum(is.na(.)), .names = "NA_{.col}"))
```

Otra forma de detectar valores faltantes
```{r otraforma}
missmap(data_cancer)
```

Ahora hagamos la imputacion de datos faltantes

```{r imp}
data_cancer %>% 
  mutate(across(
    where(is.numeric),
    ~ ifelse(is.na(.),mean(., na.rm= TRUE), .)
  )) -> df
```


Verificar si tiene datos faltantes nuevamente

```{r faltante2}
df %>% 
  summarise(across(everything(), ~sum(is.na(.)), .names = "NA_{.col}"))
```
