# EDA {#intro}

Carguemos las librerias

```{r libreria, message= FALSE, warning=FALSE}
library(tidyverse)
library(Amelia)
library(dplyr)
```

```{r data}
data <- read.csv("~/Metodos_estadisticos/Data/housing.csv")
```

Muestrame las 5 primeras filas

```{r filas}
head(data, n= 5)
```

La estructura de los datos

```{r estructura}
str(data)
```


Veamos si hay datos faltantes

```{r faltante}
data %>% 
  summarise(across(everything(), ~sum(is.na(.)), .names = "NA_{.col}"))
```

Otra forma de detectar valores faltantes
```{r otraforma}
missmap(data)
```

Ahora hagamos la imputacion de datos faltantes

```{r imp}
data %>% 
  mutate(across(
    where(is.numeric),
    ~ ifelse(is.na(.),mean(., na.rm= TRUE), .)
  )) -> df
```


Verificar si tiene datos faltantes nuevamente

```{r faltante2}
df %>% 
  summarise(across(everything(), ~sum(is.na(.)), .names = "NA_{.col}"))
```

Vamos a convertir la variable 'ocean_proximity' en un factor

```{r factorocean}
df$ocean_proximity <- factor(df$ocean_proximity)
```

