<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 1 EDA | 02-EDA.knit</title>
  <meta name="description" content="" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 1 EDA | 02-EDA.knit" />
  <meta property="og:type" content="book" />
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 1 EDA | 02-EDA.knit" />
  
  
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  


<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path=""><a href="#EDA"><i class="fa fa-check"></i><b>1</b> EDA</a>
<ul>
<li class="chapter" data-level="1.1" data-path=""><a href="#an%C3%A1lisis-exploratorio-de-target_deathrate-variable-respuesta"><i class="fa fa-check"></i><b>1.1</b> Análisis exploratorio de ‘target_deathrate’ (Variable respuesta)</a></li>
<li class="chapter" data-level="1.2" data-path=""><a href="#an%C3%A1lisis-exploratorio-univariado-de-cada-variable-explicativa"><i class="fa fa-check"></i><b>1.2</b> Análisis exploratorio univariado de cada variable explicativa</a></li>
<li class="chapter" data-level="1.3" data-path=""><a href="#an%C3%A1lisis-exploratorio-univariado-de-otras-variables-pertinentes"><i class="fa fa-check"></i><b>1.3</b> Análisis exploratorio univariado de otras variables pertinentes</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./"></a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<!--bookdown:title:end-->
<!--bookdown:title:start-->
<div id="EDA" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> EDA<a href="#EDA" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Carguemos las librerias</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(Amelia)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb1-5"><a href="#cb1-5" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-6"><a href="#cb1-6" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb1-7"><a href="#cb1-7" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb1-8"><a href="#cb1-8" tabindex="-1"></a><span class="fu">library</span>(effsize)</span>
<span id="cb1-9"><a href="#cb1-9" tabindex="-1"></a><span class="fu">library</span>(openintro)</span>
<span id="cb1-10"><a href="#cb1-10" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb1-11"><a href="#cb1-11" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb1-12"><a href="#cb1-12" tabindex="-1"></a><span class="fu">library</span>(coin)</span>
<span id="cb1-13"><a href="#cb1-13" tabindex="-1"></a><span class="fu">library</span>(BSDA)</span>
<span id="cb1-14"><a href="#cb1-14" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span></code></pre></div>
<p>Conjunto de datos</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a>data_cancer <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Data/cancer_reg.csv&quot;</span>)</span></code></pre></div>
<p>Muestrame las 5 primeras filas</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" tabindex="-1"></a><span class="fu">head</span>(data_cancer, <span class="at">n=</span> <span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   avganncount avgdeathsperyear target_deathrate incidencerate medincome
## 1        1397              469            164.9         489.8     61898
## 2         173               70            161.3         411.6     48127
## 3         102               50            174.7         349.7     49348
## 4         427              202            194.8         430.4     44243
## 5          57               26            144.4         350.1     49955
##   popest2015 povertypercent studypercap          binnedinc medianage
## 1     260131           11.2   499.74820  (61494.5, 125635]      39.3
## 2      43269           18.6    23.11123 (48021.6, 51046.4]      33.0
## 3      21026           14.6    47.56016 (48021.6, 51046.4]      45.0
## 4      75882           17.1   342.63725   (42724.4, 45201]      42.8
## 5      10321           12.5     0.00000 (48021.6, 51046.4]      48.3
##   medianagemale medianagefemale                    geography percentmarried
## 1          36.9            41.7    Kitsap County, Washington           52.5
## 2          32.2            33.7  Kittitas County, Washington           44.5
## 3          44.0            45.8 Klickitat County, Washington           54.2
## 4          42.2            43.4     Lewis County, Washington           52.7
## 5          47.8            48.9   Lincoln County, Washington           57.8
##   pctnohs18_24 pcths18_24 pctsomecol18_24 pctbachdeg18_24 pcths25_over
## 1         11.5       39.5            42.1             6.9         23.2
## 2          6.1       22.4            64.0             7.5         26.0
## 3         24.0       36.6              NA             9.5         29.0
## 4         20.2       41.2            36.1             2.5         31.6
## 5         14.9       43.0            40.0             2.0         33.4
##   pctbachdeg25_over pctemployed16_over pctunemployed16_over pctprivatecoverage
## 1              19.6               51.9                  8.0               75.1
## 2              22.7               55.9                  7.8               70.2
## 3              16.0               45.9                  7.0               63.7
## 4               9.3               48.3                 12.1               58.4
## 5              15.0               48.2                  4.8               61.6
##   pctprivatecoveragealone pctempprivcoverage pctpubliccoverage
## 1                      NA               41.6              32.9
## 2                    53.8               43.6              31.1
## 3                    43.5               34.9              42.1
## 4                    40.3               35.0              45.3
## 5                    43.9               35.1              44.0
##   pctpubliccoveragealone pctwhite  pctblack  pctasian pctotherrace
## 1                   14.0 81.78053 2.5947283 4.8218571    1.8434785
## 2                   15.3 89.22851 0.9691025 2.2462326    3.7413515
## 3                   21.1 90.92219 0.7396734 0.4658982    2.7473583
## 4                   25.0 91.74469 0.7826260 1.1613587    1.3626432
## 5                   22.7 94.10402 0.2701920 0.6658304    0.4921355
##   pctmarriedhouseholds birthrate
## 1             52.85608  6.118831
## 2             45.37250  4.333096
## 3             54.44487  3.729488
## 4             51.02151  4.603841
## 5             54.02746  6.796657</code></pre>
<p>La estructura de los datos</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" tabindex="-1"></a><span class="fu">str</span>(data_cancer)</span></code></pre></div>
<pre><code>## &#39;data.frame&#39;:    3047 obs. of  33 variables:
##  $ avganncount            : num  1397 173 102 427 57 ...
##  $ avgdeathsperyear       : int  469 70 50 202 26 152 97 71 36 1380 ...
##  $ target_deathrate       : num  165 161 175 195 144 ...
##  $ incidencerate          : num  490 412 350 430 350 ...
##  $ medincome              : int  61898 48127 49348 44243 49955 52313 37782 40189 42579 60397 ...
##  $ popest2015             : int  260131 43269 21026 75882 10321 61023 41516 20848 13088 843954 ...
##  $ povertypercent         : num  11.2 18.6 14.6 17.1 12.5 15.6 23.2 17.8 22.3 13.1 ...
##  $ studypercap            : num  499.7 23.1 47.6 342.6 0 ...
##  $ binnedinc              : chr  &quot;(61494.5, 125635]&quot; &quot;(48021.6, 51046.4]&quot; &quot;(48021.6, 51046.4]&quot; &quot;(42724.4, 45201]&quot; ...
##  $ medianage              : num  39.3 33 45 42.8 48.3 45.4 42.6 51.7 49.3 35.8 ...
##  $ medianagemale          : num  36.9 32.2 44 42.2 47.8 43.5 42.2 50.8 48.4 34.7 ...
##  $ medianagefemale        : num  41.7 33.7 45.8 43.4 48.9 48 43.5 52.5 49.8 37 ...
##  $ geography              : chr  &quot;Kitsap County, Washington&quot; &quot;Kittitas County, Washington&quot; &quot;Klickitat County, Washington&quot; &quot;Lewis County, Washington&quot; ...
##  $ percentmarried         : num  52.5 44.5 54.2 52.7 57.8 50.4 54.1 52.7 55.9 50 ...
##  $ pctnohs18_24           : num  11.5 6.1 24 20.2 14.9 29.9 26.1 27.3 34.7 15.6 ...
##  $ pcths18_24             : num  39.5 22.4 36.6 41.2 43 35.1 41.4 33.9 39.4 36.3 ...
##  $ pctsomecol18_24        : num  42.1 64 NA 36.1 40 NA NA 36.5 NA NA ...
##  $ pctbachdeg18_24        : num  6.9 7.5 9.5 2.5 2 4.5 5.8 2.2 1.4 7.1 ...
##  $ pcths25_over           : num  23.2 26 29 31.6 33.4 30.4 29.8 31.6 32.2 28.8 ...
##  $ pctbachdeg25_over      : num  19.6 22.7 16 9.3 15 11.9 11.9 11.3 12 16.2 ...
##  $ pctemployed16_over     : num  51.9 55.9 45.9 48.3 48.2 44.1 51.8 40.9 39.5 56.6 ...
##  $ pctunemployed16_over   : num  8 7.8 7 12.1 4.8 12.9 8.9 8.9 10.3 9.2 ...
##  $ pctprivatecoverage     : num  75.1 70.2 63.7 58.4 61.6 60 49.5 55.8 55.5 69.9 ...
##  $ pctprivatecoveragealone: num  NA 53.8 43.5 40.3 43.9 38.8 35 33.1 37.8 NA ...
##  $ pctempprivcoverage     : num  41.6 43.6 34.9 35 35.1 32.6 28.3 25.9 29.9 44.4 ...
##  $ pctpubliccoverage      : num  32.9 31.1 42.1 45.3 44 43.2 46.4 50.9 48.1 31.4 ...
##  $ pctpubliccoveragealone : num  14 15.3 21.1 25 22.7 20.2 28.7 24.1 26.6 16.5 ...
##  $ pctwhite               : num  81.8 89.2 90.9 91.7 94.1 ...
##  $ pctblack               : num  2.595 0.969 0.74 0.783 0.27 ...
##  $ pctasian               : num  4.822 2.246 0.466 1.161 0.666 ...
##  $ pctotherrace           : num  1.843 3.741 2.747 1.363 0.492 ...
##  $ pctmarriedhouseholds   : num  52.9 45.4 54.4 51 54 ...
##  $ birthrate              : num  6.12 4.33 3.73 4.6 6.8 ...</code></pre>
<p>Veamos si hay datos faltantes</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a>data_cancer <span class="sc">%&gt;%</span> </span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_avganncount NA_avgdeathsperyear NA_target_deathrate NA_incidencerate
## 1              0                   0                   0                0
##   NA_medincome NA_popest2015 NA_povertypercent NA_studypercap NA_binnedinc
## 1            0             0                 0              0            0
##   NA_medianage NA_medianagemale NA_medianagefemale NA_geography
## 1            0                0                  0            0
##   NA_percentmarried NA_pctnohs18_24 NA_pcths18_24 NA_pctsomecol18_24
## 1                 0               0             0               2285
##   NA_pctbachdeg18_24 NA_pcths25_over NA_pctbachdeg25_over NA_pctemployed16_over
## 1                  0               0                    0                   152
##   NA_pctunemployed16_over NA_pctprivatecoverage NA_pctprivatecoveragealone
## 1                       0                     0                        609
##   NA_pctempprivcoverage NA_pctpubliccoverage NA_pctpubliccoveragealone
## 1                     0                    0                         0
##   NA_pctwhite NA_pctblack NA_pctasian NA_pctotherrace NA_pctmarriedhouseholds
## 1           0           0           0               0                       0
##   NA_birthrate
## 1            0</code></pre>
<p>Otra forma de detectar valores faltantes</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a><span class="fu">missmap</span>(data_cancer)</span></code></pre></div>
<p><img src="02-EDA_files/figure-html/otraforma-1.png" alt="" width="672" /></p>
<p>Ahora hagamos la imputacion de datos faltantes</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" tabindex="-1"></a>data_cancer <span class="sc">%&gt;%</span> </span>
<span id="cb10-2"><a href="#cb10-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(</span>
<span id="cb10-3"><a href="#cb10-3" tabindex="-1"></a>    <span class="fu">where</span>(is.numeric),</span>
<span id="cb10-4"><a href="#cb10-4" tabindex="-1"></a>    <span class="sc">~</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(.),<span class="fu">mean</span>(., <span class="at">na.rm=</span> <span class="cn">TRUE</span>), .)</span>
<span id="cb10-5"><a href="#cb10-5" tabindex="-1"></a>  )) <span class="ot">-&gt;</span> df</span></code></pre></div>
<p>Verificar si tiene datos faltantes nuevamente</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb11-2"><a href="#cb11-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_avganncount NA_avgdeathsperyear NA_target_deathrate NA_incidencerate
## 1              0                   0                   0                0
##   NA_medincome NA_popest2015 NA_povertypercent NA_studypercap NA_binnedinc
## 1            0             0                 0              0            0
##   NA_medianage NA_medianagemale NA_medianagefemale NA_geography
## 1            0                0                  0            0
##   NA_percentmarried NA_pctnohs18_24 NA_pcths18_24 NA_pctsomecol18_24
## 1                 0               0             0                  0
##   NA_pctbachdeg18_24 NA_pcths25_over NA_pctbachdeg25_over NA_pctemployed16_over
## 1                  0               0                    0                     0
##   NA_pctunemployed16_over NA_pctprivatecoverage NA_pctprivatecoveragealone
## 1                       0                     0                          0
##   NA_pctempprivcoverage NA_pctpubliccoverage NA_pctpubliccoveragealone
## 1                     0                    0                         0
##   NA_pctwhite NA_pctblack NA_pctasian NA_pctotherrace NA_pctmarriedhouseholds
## 1           0           0           0               0                       0
##   NA_birthrate
## 1            0</code></pre>
<div id="análisis-exploratorio-de-target_deathrate-variable-respuesta" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Análisis exploratorio de ‘target_deathrate’ (Variable respuesta)<a href="#an%C3%A1lisis-exploratorio-de-target_deathrate-variable-respuesta" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>A continuación, se presentan una función para generar la tabla exploratoria univariada de una variable numérica</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>summarise_numeric <span class="ot">&lt;-</span> <span class="cf">function</span>(df, var) {</span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>  df <span class="sc">%&gt;%</span> </span>
<span id="cb13-3"><a href="#cb13-3" tabindex="-1"></a>    <span class="fu">summarise</span>(</span>
<span id="cb13-4"><a href="#cb13-4" tabindex="-1"></a>      <span class="at">n =</span> <span class="fu">n</span>(),</span>
<span id="cb13-5"><a href="#cb13-5" tabindex="-1"></a>      <span class="at">media =</span> <span class="fu">mean</span>({{ var }}), </span>
<span id="cb13-6"><a href="#cb13-6" tabindex="-1"></a>      <span class="at">desv_est =</span> <span class="fu">sd</span>({{ var }}),</span>
<span id="cb13-7"><a href="#cb13-7" tabindex="-1"></a>      <span class="at">mediana =</span> <span class="fu">median</span>({{ var }}), </span>
<span id="cb13-8"><a href="#cb13-8" tabindex="-1"></a>      <span class="at">RIC =</span> <span class="fu">IQR</span>({{ var }}), </span>
<span id="cb13-9"><a href="#cb13-9" tabindex="-1"></a>      <span class="at">Q1 =</span> <span class="fu">quantile</span>({{ var }}, <span class="fl">0.25</span>), </span>
<span id="cb13-10"><a href="#cb13-10" tabindex="-1"></a>      <span class="at">Q3 =</span> <span class="fu">quantile</span>({{ var }}, <span class="fl">0.75</span>), </span>
<span id="cb13-11"><a href="#cb13-11" tabindex="-1"></a>      <span class="at">min =</span> <span class="fu">min</span>({{ var }}), </span>
<span id="cb13-12"><a href="#cb13-12" tabindex="-1"></a>      <span class="at">max =</span> <span class="fu">max</span>({{ var }}), </span>
<span id="cb13-13"><a href="#cb13-13" tabindex="-1"></a>      <span class="at">curtosis =</span> <span class="fu">kurtosis</span>({{ var }}), </span>
<span id="cb13-14"><a href="#cb13-14" tabindex="-1"></a>      <span class="at">Coef_asim =</span> <span class="fu">skewness</span>({{ var }})</span>
<span id="cb13-15"><a href="#cb13-15" tabindex="-1"></a>    )</span>
<span id="cb13-16"><a href="#cb13-16" tabindex="-1"></a>}</span></code></pre></div>
<p>Realicemos el resumen estadístico de la variable <code>target_deathrate</code></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a><span class="fu">summarise_numeric</span>(df, target_deathrate)</span></code></pre></div>
<pre><code>##      n    media desv_est mediana RIC    Q1    Q3  min   max curtosis Coef_asim
## 1 3047 178.6641 27.75151   178.1  34 161.2 195.2 59.7 362.8 4.350431 0.2745889</code></pre>
<p>Se registraron un total de 3047 registros de tasas de muertes causadas por cáncer con una tasa media de 178.66 (DE = 27.75). Además, el 50% de las tasas de muerte son menores o iguales a 178.1 (RIC = 34), es decir, son muy cercanos a la media, lo que sugiere una distribución relativamente
centrada. Por otro lado, el 25% son a lo sumo 161.2, y el 75% no supera 195.2. Además, el rango de los datos es de 303.1, siendo la tasa mínima 59.7 y la máxima 362.8. Por otro lado, se evidencia que las tasas de muerte poseen una forma leptocúrtica (curtosis = 4.35&gt;3), es decir, con un pico algo más marcado y colas más pesadas que la normal. Además, los datos presentan una ligera asimetría positiva o sesgo hacia la derecha (Coef_asim = 0.27), con lo cual se observa que existen algunas tasas excesivamente más altas que la mayoría.</p>
<p>A continuación, se presentan una función para generar los gráficos exploratorios univariados de una variable numérica</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a>plot_univariado <span class="ot">&lt;-</span> <span class="cf">function</span>(df, var) {</span>
<span id="cb16-2"><a href="#cb16-2" tabindex="-1"></a>  <span class="co"># Boxplot</span></span>
<span id="cb16-3"><a href="#cb16-3" tabindex="-1"></a>  p_box <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="#cb16-4" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> {{ var }})) <span class="sc">+</span></span>
<span id="cb16-5"><a href="#cb16-5" tabindex="-1"></a>    <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#8ecae6&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#023047&quot;</span>, </span>
<span id="cb16-6"><a href="#cb16-6" tabindex="-1"></a>                 <span class="at">outlier.color =</span> <span class="st">&quot;#e63946&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" tabindex="-1"></a>    <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;#023047&#39;</span>) <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Diagrama de cajas y bigotes&quot;</span>, <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> rlang<span class="sc">::</span><span class="fu">as_label</span>(rlang<span class="sc">::</span><span class="fu">enquo</span>(var))) <span class="sc">+</span></span>
<span id="cb16-9"><a href="#cb16-9" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span>
<span id="cb16-10"><a href="#cb16-10" tabindex="-1"></a>  <span class="co"># Histograma de polígonos</span></span>
<span id="cb16-11"><a href="#cb16-11" tabindex="-1"></a>  p_hist <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb16-12"><a href="#cb16-12" tabindex="-1"></a>    <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> {{ var }})) <span class="sc">+</span></span>
<span id="cb16-13"><a href="#cb16-13" tabindex="-1"></a>    <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(count)), <span class="at">fill =</span> <span class="st">&quot;#8ecae6&quot;</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb16-14"><a href="#cb16-14" tabindex="-1"></a>    <span class="fu">geom_freqpoly</span>(<span class="at">color =</span> <span class="st">&quot;#023047&quot;</span>, <span class="at">linewidth =</span> <span class="dv">1</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>, <span class="at">bins =</span> <span class="dv">30</span>) <span class="sc">+</span></span>
<span id="cb16-15"><a href="#cb16-15" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Histograma de polígonos&quot;</span>, <span class="at">x =</span> rlang<span class="sc">::</span><span class="fu">as_label</span>(rlang<span class="sc">::</span><span class="fu">enquo</span>(var)), <span class="at">y =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-16"><a href="#cb16-16" tabindex="-1"></a>    <span class="fu">theme_bw</span>()</span>
<span id="cb16-17"><a href="#cb16-17" tabindex="-1"></a>  <span class="co"># Combinar los dos plots</span></span>
<span id="cb16-18"><a href="#cb16-18" tabindex="-1"></a>  p_hist <span class="sc">+</span> p_box</span>
<span id="cb16-19"><a href="#cb16-19" tabindex="-1"></a>}</span></code></pre></div>
<p>Observemos la distribución de la variable objetivo <code>target_deathrate</code> a través de un diagrama de cajas y bigotes y un histograma de polígonos</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" tabindex="-1"></a><span class="fu">plot_univariado</span>(df, target_deathrate)</span></code></pre></div>
<p><img src="02-EDA_files/figure-html/univTarget-1.png" alt="" width="672" /></p>
<p>La distribución de <code>target_deathrate</code> presenta una ligera asimetría a la
derecha, confirmando lo expuesto por el coeficiente de asimetría positivo.
Además, la variable cuenta con un número considerable de valores atípicos
tanto en la cola inferior como en la superior, es decir, existen regiones
con tasas de muerte muy alejadas de la mayoría, particularmente
por encima de 250 y por debajo de 110 aproximadamente.</p>
<p>Por otro lado, la media (178.66) es prácticamente igual a la mediana (178.1), lo cual es consistente con una distribución casi simétrica en su núcleo central, a pesar de la ligera asimetría generada por los valores extremos en la cola derecha. La forma del histograma exhibe un pico marcado alrededor del valor central, lo que respalda la forma leptocúrtica previamente hallada (curtosis = 4.35), indicando una mayor concentración de datos cerca de la media y colas más pesadas que las de una distribución normal.</p>
<p>La presencia simultánea de valores atípicos en ambos extremos sugiere una
heterogeneidad importante entre regiones: mientras algunas zonas presentan
tasas de mortalidad excepcionalmente bajas (posiblemente asociadas a mejor
acceso a salud o detección temprana), otras muestran tasas alarmantemente
altas, lo que podría estar vinculado a factores socioeconómicos adversos
como pobreza elevada o baja cobertura médica, variables que se explorarán
más adelante en el análisis.</p>
</div>
<div id="análisis-exploratorio-univariado-de-cada-variable-explicativa" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Análisis exploratorio univariado de cada variable explicativa<a href="#an%C3%A1lisis-exploratorio-univariado-de-cada-variable-explicativa" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a><span class="fu">summarise_numeric</span>(df, povertypercent)</span></code></pre></div>
<pre><code>##      n    media desv_est mediana  RIC    Q1   Q3 min  max curtosis Coef_asim
## 1 3047 16.87818 6.409087    15.9 8.25 12.15 20.4 3.2 47.4 4.272006 0.9302543</code></pre>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" tabindex="-1"></a><span class="fu">plot_univariado</span>(df, povertypercent)</span></code></pre></div>
<p><img src="02-EDA_files/figure-html/povertypercentUniv-1.png" alt="" width="672" /></p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">summarise_numeric</span>(df, medincome)</span></code></pre></div>
<pre><code>##      n    media desv_est mediana     RIC      Q1    Q3   min    max curtosis
## 1 3047 47063.28 12040.09   45207 13609.5 38882.5 52492 22640 125635 6.705259
##   Coef_asim
## 1  1.407377</code></pre>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a><span class="fu">plot_univariado</span>(df, medincome)</span></code></pre></div>
<p><img src="02-EDA_files/figure-html/medincomeUniv-1.png" alt="" width="672" /></p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a><span class="fu">summarise_numeric</span>(df, pctbachdeg25_over)</span></code></pre></div>
<pre><code>##      n    media desv_est mediana RIC  Q1   Q3 min  max curtosis Coef_asim
## 1 3047 13.28202 5.394756    12.3 6.7 9.4 16.1 2.5 42.2  4.73255  1.094298</code></pre>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" tabindex="-1"></a><span class="fu">plot_univariado</span>(df, pctbachdeg25_over)</span></code></pre></div>
<p><img src="02-EDA_files/figure-html/pctbachdeg25_overUniv-1.png" alt="" width="672" /></p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" tabindex="-1"></a><span class="fu">summarise_numeric</span>(df, pctprivatecoverage)</span></code></pre></div>
<pre><code>##      n    media desv_est mediana  RIC   Q1   Q3  min  max curtosis  Coef_asim
## 1 3047 64.35494 10.64706    65.1 14.9 57.2 72.1 22.3 92.3 2.994335 -0.3933435</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" tabindex="-1"></a><span class="fu">plot_univariado</span>(df, pctprivatecoverage)</span></code></pre></div>
<p><img src="02-EDA_files/figure-html/pctprivatecoverageUniv-1.png" alt="" width="672" /></p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" tabindex="-1"></a><span class="fu">summarise_numeric</span>(df, pctpubliccoverage)</span></code></pre></div>
<pre><code>##      n    media desv_est mediana   RIC   Q1    Q3  min  max curtosis
## 1 3047 36.25264 7.841741    36.3 10.65 30.9 41.55 11.2 65.1 2.908984
##      Coef_asim
## 1 -0.005432924</code></pre>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" tabindex="-1"></a><span class="fu">plot_univariado</span>(df, pctpubliccoverage)</span></code></pre></div>
<p><img src="02-EDA_files/figure-html/pctpubliccoverageUniv-1.png" alt="" width="672" /></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" tabindex="-1"></a><span class="fu">summarise_numeric</span>(df, pctunemployed16_over)</span></code></pre></div>
<pre><code>##      n    media desv_est mediana RIC  Q1  Q3 min  max curtosis Coef_asim
## 1 3047 7.852412 3.452371     7.6 4.2 5.5 9.7 0.4 29.4 5.291033 0.8906224</code></pre>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" tabindex="-1"></a><span class="fu">plot_univariado</span>(df, pctunemployed16_over)</span></code></pre></div>
<p><img src="02-EDA_files/figure-html/pctunemployed16_overUniv-1.png" alt="" width="672" /></p>
</div>
<div id="análisis-exploratorio-univariado-de-otras-variables-pertinentes" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Análisis exploratorio univariado de otras variables pertinentes<a href="#an%C3%A1lisis-exploratorio-univariado-de-otras-variables-pertinentes" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" tabindex="-1"></a><span class="fu">summarise_numeric</span>(df, incidencerate)</span></code></pre></div>
<pre><code>##      n    media desv_est  mediana   RIC    Q1     Q3   min    max curtosis
## 1 3047 448.2686 54.56073 453.5494 60.55 420.3 480.85 201.3 1206.9 19.76697
##   Coef_asim
## 1 0.7715547</code></pre>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" tabindex="-1"></a><span class="co">#summarise_char(df, binnedinc)</span></span></code></pre></div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>


    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/%s",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": false,
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
