--- 
title: "Proyecto de Métodos Estadísticos"
author: "Sebastian Ariza y Joseph Arias"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: j0s23/Libro
description: "Aquí voy a realizar el trabajo aplicado de la asignatura de métodos estadísticos"
---

# Introducción {-}

El presente libro recopila el trabajo aplicado de la asignatura de Métodos Estadísticos, organizado en dos capítulos. El primero desarrolla el análisis exploratorio de datos (EDA) sobre el dataset de viviendas de California: manejo de datos faltantes, análisis univariado y bivariado de las variables, y una ingeniería de características que reduce la redundancia entre las variables de tamaño altamente correlacionadas. El segundo capítulo aplica pruebas de hipótesis paramétricas y no paramétricas sobre cuatro conjuntos de datos: comparación de dos medias (presión arterial y precios según tipo de cuenta), prueba pareada (intervención educativa), contraste entre t-test y Mann-Whitney (peso al nacer según hábito de fumar) y ANOVA de un factor, junto con el test de Wilcoxon pareado para datos ordinales.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
