<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Análisis paramétrico y no paramétrico | Proyecto de Métodos Estadísticos</title>
  <meta name="description" content="Aquí voy a realizar el trabajo aplicado de la asignatura de métodos estadísticos" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Análisis paramétrico y no paramétrico | Proyecto de Métodos Estadísticos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Aquí voy a realizar el trabajo aplicado de la asignatura de métodos estadísticos" />
  <meta name="github-repo" content="j0s23/Libro" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Análisis paramétrico y no paramétrico | Proyecto de Métodos Estadísticos" />
  
  <meta name="twitter:description" content="Aquí voy a realizar el trabajo aplicado de la asignatura de métodos estadísticos" />
  

<meta name="author" content="Sebastian Ariza y Joseph Arias" />


<meta name="date" content="2026-09-15" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="metodología.html"/>
<link rel="next" href="referencias.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="introducción.html"><a href="introducción.html"><i class="fa fa-check"></i>Introducción</a></li>
<li class="chapter" data-level="1" data-path="EDA.html"><a href="EDA.html"><i class="fa fa-check"></i><b>1</b> EDA</a>
<ul>
<li class="chapter" data-level="1.1" data-path="EDA.html"><a href="EDA.html#an%C3%A1lisis-exploratorio-de-target_deathrate-variable-respuesta"><i class="fa fa-check"></i><b>1.1</b> Análisis exploratorio de ‘target_deathrate’ (Variable respuesta)</a></li>
<li class="chapter" data-level="1.2" data-path="EDA.html"><a href="EDA.html#an%C3%A1lisis-exploratorio-univariado-de-cada-variable-explicativa"><i class="fa fa-check"></i><b>1.2</b> Análisis exploratorio univariado de cada variable explicativa</a></li>
<li class="chapter" data-level="1.3" data-path="EDA.html"><a href="EDA.html#an%C3%A1lisis-exploratorio-univariado-de-la-variable-categ%C3%B3rica-binnedinc"><i class="fa fa-check"></i><b>1.3</b> Análisis exploratorio univariado de la variable categórica <code>binnedinc</code></a></li>
<li class="chapter" data-level="1.4" data-path="EDA.html"><a href="EDA.html#an%C3%A1lisis-exploratorio-bivariado-entre-la-variable-dependiente-y-las-variables-independientes"><i class="fa fa-check"></i><b>1.4</b> Análisis exploratorio bivariado entre la variable dependiente y las variables independientes</a></li>
<li class="chapter" data-level="1.5" data-path="EDA.html"><a href="EDA.html#an%C3%A1lisis-exploratorio-bivariado-de-las-variables-independientes-entre-s%C3%AD"><i class="fa fa-check"></i><b>1.5</b> Análisis exploratorio bivariado de las variables independientes entre sí</a></li>
<li class="chapter" data-level="1.6" data-path="EDA.html"><a href="EDA.html#an%C3%A1lisis-exploratorio-bivariado-entre-las-variables-independientes-y-la-variable-categ%C3%B3rica"><i class="fa fa-check"></i><b>1.6</b> Análisis exploratorio bivariado entre las variables independientes y la variable categórica</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="metodología.html"><a href="metodología.html"><i class="fa fa-check"></i>Metodología</a>
<ul>
<li class="chapter" data-level="1.7" data-path="metodología.html"><a href="metodología.html#fuente-y-preparaci%C3%B3n-de-los-datos"><i class="fa fa-check"></i><b>1.7</b> Fuente y preparación de los datos</a></li>
<li class="chapter" data-level="1.8" data-path="metodología.html"><a href="metodología.html#objetivo-1-evaluaci%C3%B3n-de-supuestos-de-normalidad-y-homocedasticidad"><i class="fa fa-check"></i><b>1.8</b> Objetivo 1: Evaluación de supuestos de normalidad y homocedasticidad</a></li>
<li class="chapter" data-level="1.9" data-path="metodología.html"><a href="metodología.html#objetivo-2-comparaci%C3%B3n-de-medias-entre-grupos-de-pobreza"><i class="fa fa-check"></i><b>1.9</b> Objetivo 2: Comparación de medias entre grupos de pobreza</a></li>
<li class="chapter" data-level="1.10" data-path="metodología.html"><a href="metodología.html#objetivo-3-cuantificaci%C3%B3n-de-la-asociaci%C3%B3n-lineal"><i class="fa fa-check"></i><b>1.10</b> Objetivo 3: Cuantificación de la asociación lineal</a></li>
<li class="chapter" data-level="1.11" data-path="metodología.html"><a href="metodología.html#objetivo-4-efecto-del-balance-de-cobertura-m%C3%A9dica-sobre-la-mortalidad"><i class="fa fa-check"></i><b>1.11</b> Objetivo 4: Efecto del balance de cobertura médica sobre la mortalidad</a></li>
<li class="chapter" data-level="1.12" data-path="metodología.html"><a href="metodología.html#objetivo-5-asociaci%C3%B3n-entre-nivel-de-ingreso-y-nivel-de-mortalidad"><i class="fa fa-check"></i><b>1.12</b> Objetivo 5: Asociación entre nivel de ingreso y nivel de mortalidad</a></li>
<li class="chapter" data-level="1.13" data-path="metodología.html"><a href="metodología.html#nivel-de-significancia"><i class="fa fa-check"></i><b>1.13</b> Nivel de significancia</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="Análisis_estadístico.html"><a href="Análisis_estadístico.html"><i class="fa fa-check"></i><b>2</b> Análisis paramétrico y no paramétrico</a>
<ul>
<li class="chapter" data-level="2.1" data-path="Análisis_estadístico.html"><a href="Análisis_estadístico.html#librer%C3%ADas"><i class="fa fa-check"></i><b>2.1</b> Librerías</a></li>
<li class="chapter" data-level="2.2" data-path="Análisis_estadístico.html"><a href="Análisis_estadístico.html#objetivo-3.-cuantificar-la-asociaci%C3%B3n-lineal"><i class="fa fa-check"></i><b>2.2</b> Objetivo #3. Cuantificar la asociación lineal</a></li>
<li class="chapter" data-level="2.3" data-path="Análisis_estadístico.html"><a href="Análisis_estadístico.html#objetivo-4.-contrastar-el-efecto-del-balance-de-cobertura-m%C3%A9dica"><i class="fa fa-check"></i><b>2.3</b> Objetivo #4. Contrastar el efecto del balance de cobertura médica</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias.html"><a href="referencias.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="chapter" data-level="" data-path="abstract.html"><a href="abstract.html"><i class="fa fa-check"></i>Abstract</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Proyecto de Métodos Estadísticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="Análisis_estadístico" class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Análisis paramétrico y no paramétrico<a href="Análisis_estadístico.html#An%C3%A1lisis_estad%C3%ADstico" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div id="librerías" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Librerías<a href="Análisis_estadístico.html#librer%C3%ADas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb75"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb75-1"><a href="Análisis_estadístico.html#cb75-1" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb75-2"><a href="Análisis_estadístico.html#cb75-2" tabindex="-1"></a><span class="fu">library</span>(moments)</span>
<span id="cb75-3"><a href="Análisis_estadístico.html#cb75-3" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb75-4"><a href="Análisis_estadístico.html#cb75-4" tabindex="-1"></a><span class="fu">library</span>(effsize)</span>
<span id="cb75-5"><a href="Análisis_estadístico.html#cb75-5" tabindex="-1"></a><span class="fu">library</span>(openintro)</span>
<span id="cb75-6"><a href="Análisis_estadístico.html#cb75-6" tabindex="-1"></a><span class="fu">library</span>(nortest)</span>
<span id="cb75-7"><a href="Análisis_estadístico.html#cb75-7" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb75-8"><a href="Análisis_estadístico.html#cb75-8" tabindex="-1"></a><span class="fu">library</span>(coin)</span>
<span id="cb75-9"><a href="Análisis_estadístico.html#cb75-9" tabindex="-1"></a><span class="fu">library</span>(BSDA)</span>
<span id="cb75-10"><a href="Análisis_estadístico.html#cb75-10" tabindex="-1"></a><span class="fu">library</span>(rstatix)</span></code></pre></div>
<p>Se cargan los datos de cáncer.</p>
<div class="sourceCode" id="cb76"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb76-1"><a href="Análisis_estadístico.html#cb76-1" tabindex="-1"></a>data_cancer <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;Data/cancer_reg.csv&quot;</span>)</span>
<span id="cb76-2"><a href="Análisis_estadístico.html#cb76-2" tabindex="-1"></a></span>
<span id="cb76-3"><a href="Análisis_estadístico.html#cb76-3" tabindex="-1"></a><span class="fu">summary</span>(data_cancer)</span></code></pre></div>
<pre><code>##   avganncount      avgdeathsperyear target_deathrate incidencerate      medincome     
##  Min.   :    6.0   Min.   :    3    Min.   : 59.7    Min.   : 201.3   Min.   : 22640  
##  1st Qu.:   76.0   1st Qu.:   28    1st Qu.:161.2    1st Qu.: 420.3   1st Qu.: 38883  
##  Median :  171.0   Median :   61    Median :178.1    Median : 453.5   Median : 45207  
##  Mean   :  606.3   Mean   :  186    Mean   :178.7    Mean   : 448.3   Mean   : 47063  
##  3rd Qu.:  518.0   3rd Qu.:  149    3rd Qu.:195.2    3rd Qu.: 480.9   3rd Qu.: 52492  
##  Max.   :38150.0   Max.   :14010    Max.   :362.8    Max.   :1206.9   Max.   :125635  
##                                                                                       
##    popest2015       povertypercent   studypercap       binnedinc           medianage     
##  Min.   :     827   Min.   : 3.20   Min.   :   0.00   Length:3047        Min.   : 22.30  
##  1st Qu.:   11684   1st Qu.:12.15   1st Qu.:   0.00   Class :character   1st Qu.: 37.70  
##  Median :   26643   Median :15.90   Median :   0.00   Mode  :character   Median : 41.00  
##  Mean   :  102637   Mean   :16.88   Mean   : 155.40                      Mean   : 45.27  
##  3rd Qu.:   68671   3rd Qu.:20.40   3rd Qu.:  83.65                      3rd Qu.: 44.00  
##  Max.   :10170292   Max.   :47.40   Max.   :9762.31                      Max.   :624.00  
##                                                                                          
##  medianagemale   medianagefemale  geography         percentmarried   pctnohs18_24     pcths18_24  
##  Min.   :22.40   Min.   :22.30   Length:3047        Min.   :23.10   Min.   : 0.00   Min.   : 0.0  
##  1st Qu.:36.35   1st Qu.:39.10   Class :character   1st Qu.:47.75   1st Qu.:12.80   1st Qu.:29.2  
##  Median :39.60   Median :42.40   Mode  :character   Median :52.40   Median :17.10   Median :34.7  
##  Mean   :39.57   Mean   :42.15                      Mean   :51.77   Mean   :18.22   Mean   :35.0  
##  3rd Qu.:42.50   3rd Qu.:45.30                      3rd Qu.:56.40   3rd Qu.:22.70   3rd Qu.:40.7  
##  Max.   :64.70   Max.   :65.70                      Max.   :72.50   Max.   :64.10   Max.   :72.5  
##                                                                                                   
##  pctsomecol18_24 pctbachdeg18_24   pcths25_over   pctbachdeg25_over pctemployed16_over
##  Min.   : 7.10   Min.   : 0.000   Min.   : 7.50   Min.   : 2.50     Min.   :17.60     
##  1st Qu.:34.00   1st Qu.: 3.100   1st Qu.:30.40   1st Qu.: 9.40     1st Qu.:48.60     
##  Median :40.40   Median : 5.400   Median :35.30   Median :12.30     Median :54.50     
##  Mean   :40.98   Mean   : 6.158   Mean   :34.80   Mean   :13.28     Mean   :54.15     
##  3rd Qu.:46.40   3rd Qu.: 8.200   3rd Qu.:39.65   3rd Qu.:16.10     3rd Qu.:60.30     
##  Max.   :79.00   Max.   :51.800   Max.   :54.80   Max.   :42.20     Max.   :80.10     
##  NA&#39;s   :2285                                                       NA&#39;s   :152       
##  pctunemployed16_over pctprivatecoverage pctprivatecoveragealone pctempprivcoverage pctpubliccoverage
##  Min.   : 0.400       Min.   :22.30      Min.   :15.70           Min.   :13.5       Min.   :11.20    
##  1st Qu.: 5.500       1st Qu.:57.20      1st Qu.:41.00           1st Qu.:34.5       1st Qu.:30.90    
##  Median : 7.600       Median :65.10      Median :48.70           Median :41.1       Median :36.30    
##  Mean   : 7.852       Mean   :64.35      Mean   :48.45           Mean   :41.2       Mean   :36.25    
##  3rd Qu.: 9.700       3rd Qu.:72.10      3rd Qu.:55.60           3rd Qu.:47.7       3rd Qu.:41.55    
##  Max.   :29.400       Max.   :92.30      Max.   :78.90           Max.   :70.7       Max.   :65.10    
##                                          NA&#39;s   :609                                                 
##  pctpubliccoveragealone    pctwhite         pctblack          pctasian        pctotherrace    
##  Min.   : 2.60          Min.   : 10.20   Min.   : 0.0000   Min.   : 0.0000   Min.   : 0.0000  
##  1st Qu.:14.85          1st Qu.: 77.30   1st Qu.: 0.6207   1st Qu.: 0.2542   1st Qu.: 0.2952  
##  Median :18.80          Median : 90.06   Median : 2.2476   Median : 0.5498   Median : 0.8262  
##  Mean   :19.24          Mean   : 83.65   Mean   : 9.1080   Mean   : 1.2540   Mean   : 1.9835  
##  3rd Qu.:23.10          3rd Qu.: 95.45   3rd Qu.:10.5097   3rd Qu.: 1.2210   3rd Qu.: 2.1780  
##  Max.   :46.60          Max.   :100.00   Max.   :85.9478   Max.   :42.6194   Max.   :41.9303  
##                                                                                               
##  pctmarriedhouseholds   birthrate     
##  Min.   :22.99        Min.   : 0.000  
##  1st Qu.:47.76        1st Qu.: 4.521  
##  Median :51.67        Median : 5.381  
##  Mean   :51.24        Mean   : 5.640  
##  3rd Qu.:55.40        3rd Qu.: 6.494  
##  Max.   :78.08        Max.   :21.326  
## </code></pre>
<p>Ahora, repitamos todas las transformaciones de datos para preparar el análisis estadístico.</p>
<p>En primer lugar, volvamos a imputar los datos faltantes</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="Análisis_estadístico.html#cb78-1" tabindex="-1"></a>data_cancer <span class="sc">%&gt;%</span> </span>
<span id="cb78-2"><a href="Análisis_estadístico.html#cb78-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(</span>
<span id="cb78-3"><a href="Análisis_estadístico.html#cb78-3" tabindex="-1"></a>    <span class="fu">where</span>(is.numeric),</span>
<span id="cb78-4"><a href="Análisis_estadístico.html#cb78-4" tabindex="-1"></a>    <span class="sc">~</span> <span class="fu">ifelse</span>(<span class="fu">is.na</span>(.),<span class="fu">mean</span>(., <span class="at">na.rm=</span> <span class="cn">TRUE</span>), .)</span>
<span id="cb78-5"><a href="Análisis_estadístico.html#cb78-5" tabindex="-1"></a>  )) <span class="ot">-&gt;</span> df</span></code></pre></div>
<p>Verificar si tiene datos faltantes nuevamente</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="Análisis_estadístico.html#cb79-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb79-2"><a href="Análisis_estadístico.html#cb79-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span><span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>))</span></code></pre></div>
<pre><code>##   NA_avganncount NA_avgdeathsperyear NA_target_deathrate NA_incidencerate NA_medincome NA_popest2015
## 1              0                   0                   0                0            0             0
##   NA_povertypercent NA_studypercap NA_binnedinc NA_medianage NA_medianagemale NA_medianagefemale
## 1                 0              0            0            0                0                  0
##   NA_geography NA_percentmarried NA_pctnohs18_24 NA_pcths18_24 NA_pctsomecol18_24 NA_pctbachdeg18_24
## 1            0                 0               0             0                  0                  0
##   NA_pcths25_over NA_pctbachdeg25_over NA_pctemployed16_over NA_pctunemployed16_over
## 1               0                    0                     0                       0
##   NA_pctprivatecoverage NA_pctprivatecoveragealone NA_pctempprivcoverage NA_pctpubliccoverage
## 1                     0                          0                     0                    0
##   NA_pctpubliccoveragealone NA_pctwhite NA_pctblack NA_pctasian NA_pctotherrace
## 1                         0           0           0           0               0
##   NA_pctmarriedhouseholds NA_birthrate
## 1                       0            0</code></pre>
<p>Aplicando nuevamente ingeniería de características entre <code>pctprivatecoverage</code> y <code>pctpubliccoverage</code>.</p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="Análisis_estadístico.html#cb81-1" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb81-2"><a href="Análisis_estadístico.html#cb81-2" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb81-3"><a href="Análisis_estadístico.html#cb81-3" tabindex="-1"></a>    <span class="at">coverage_balance =</span> pctprivatecoverage <span class="sc">-</span> pctpubliccoverage,</span>
<span id="cb81-4"><a href="Análisis_estadístico.html#cb81-4" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb81-5"><a href="Análisis_estadístico.html#cb81-5" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>pctprivatecoverage, <span class="sc">-</span>pctpubliccoverage)</span>
<span id="cb81-6"><a href="Análisis_estadístico.html#cb81-6" tabindex="-1"></a></span>
<span id="cb81-7"><a href="Análisis_estadístico.html#cb81-7" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb81-8"><a href="Análisis_estadístico.html#cb81-8" tabindex="-1"></a>  <span class="fu">select</span>(coverage_balance)<span class="sc">%&gt;%</span> </span>
<span id="cb81-9"><a href="Análisis_estadístico.html#cb81-9" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>##   coverage_balance
## 1             42.2
## 2             39.1
## 3             21.6
## 4             13.1
## 5             17.6
## 6             16.8</code></pre>
</div>
<div id="objetivo-3.-cuantificar-la-asociación-lineal" class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Objetivo #3. Cuantificar la asociación lineal<a href="Análisis_estadístico.html#objetivo-3.-cuantificar-la-asociaci%C3%B3n-lineal" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para verificar si el uso de correlación de Pearson es apropiado se evalúan los supuestos de normalidad</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="Análisis_estadístico.html#cb83-1" tabindex="-1"></a>variables_corr <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;target_deathrate&quot;</span>,<span class="st">&quot;medincome&quot;</span>, <span class="st">&quot;pctbachdeg25_over&quot;</span>, <span class="st">&quot;coverage_balance&quot;</span>, <span class="st">&quot;pctunemployed16_over&quot;</span>)</span></code></pre></div>
<p>Aplicando Shapiro-Wilk por tener menos de 5000 observaciones</p>
<div class="sourceCode" id="cb84"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb84-1"><a href="Análisis_estadístico.html#cb84-1" tabindex="-1"></a><span class="co"># Shapiro-Wilk</span></span>
<span id="cb84-2"><a href="Análisis_estadístico.html#cb84-2" tabindex="-1"></a>resultados_shapiro <span class="ot">&lt;-</span> <span class="fu">lapply</span>(variables_corr, <span class="cf">function</span>(v) {</span>
<span id="cb84-3"><a href="Análisis_estadístico.html#cb84-3" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">shapiro.test</span>(df[[v]])</span>
<span id="cb84-4"><a href="Análisis_estadístico.html#cb84-4" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">variable =</span> v, <span class="at">estadistico =</span> <span class="fu">round</span>(test<span class="sc">$</span>statistic, <span class="dv">4</span>), <span class="at">p_value =</span> <span class="fu">round</span>(test<span class="sc">$</span>p.value, <span class="dv">4</span>))</span>
<span id="cb84-5"><a href="Análisis_estadístico.html#cb84-5" tabindex="-1"></a>}) <span class="sc">%&gt;%</span> <span class="fu">bind_rows</span>()</span>
<span id="cb84-6"><a href="Análisis_estadístico.html#cb84-6" tabindex="-1"></a></span>
<span id="cb84-7"><a href="Análisis_estadístico.html#cb84-7" tabindex="-1"></a>resultados_shapiro</span></code></pre></div>
<pre><code>##                   variable estadistico p_value
## W...1     target_deathrate      0.9903       0
## W...2            medincome      0.9169       0
## W...3    pctbachdeg25_over      0.9376       0
## W...4     coverage_balance      0.9968       0
## W...5 pctunemployed16_over      0.9629       0</code></pre>
<p>Verificando con la prueba de Anderson-Darling</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="Análisis_estadístico.html#cb86-1" tabindex="-1"></a>resultados_ad <span class="ot">&lt;-</span> <span class="fu">lapply</span>(variables_corr, <span class="cf">function</span>(v) {</span>
<span id="cb86-2"><a href="Análisis_estadístico.html#cb86-2" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">ad.test</span>(df[[v]])</span>
<span id="cb86-3"><a href="Análisis_estadístico.html#cb86-3" tabindex="-1"></a>  <span class="fu">data.frame</span>(<span class="at">variable =</span> v, <span class="at">estadistico =</span> <span class="fu">round</span>(test<span class="sc">$</span>statistic, <span class="dv">4</span>), <span class="at">p_value =</span> <span class="fu">round</span>(test<span class="sc">$</span>p.value, <span class="dv">4</span>))</span>
<span id="cb86-4"><a href="Análisis_estadístico.html#cb86-4" tabindex="-1"></a>}) <span class="sc">%&gt;%</span> <span class="fu">bind_rows</span>()</span>
<span id="cb86-5"><a href="Análisis_estadístico.html#cb86-5" tabindex="-1"></a></span>
<span id="cb86-6"><a href="Análisis_estadístico.html#cb86-6" tabindex="-1"></a>resultados_ad</span></code></pre></div>
<pre><code>##                   variable estadistico p_value
## A...1     target_deathrate      4.0742       0
## A...2            medincome     47.2850       0
## A...3    pctbachdeg25_over     42.1478       0
## A...4     coverage_balance      2.0212       0
## A...5 pctunemployed16_over     14.5589       0</code></pre>
<p>Tanto la prueba de Shapiro-Wilk como la prueba de Anderson-Darling confirman
resultados consistentes entre sí: con un 95% de confianza, se rechaza la
hipótesis de normalidad para las cinco variables evaluadas, ya que todos
los p-valores obtenidos son menores a 0.01 (prácticamente iguales a 0).
Esto indica que ni la variable respuesta (<code>target_deathrate</code>) ni ninguna de
las variables predictoras (<code>medincome</code>, <code>pctbachdeg25_over</code>,
<code>coverage_balance</code>, <code>pctunemployed16_over</code>) sigue una distribución normal.</p>
<p>Es importante destacar que <code>coverage_balance</code> presenta el estadístico de
Shapiro-Wilk más cercano a 1 (W = 0.9968) y el valor más bajo de
Anderson-Darling (A = 2.02) entre todas las variables, lo cual sugiere que,
aunque el supuesto de normalidad se rechaza formalmente por el tamaño
muestral, esta variable es la que más se aproxima a un comportamiento
normal —consistente con lo observado en el EDA, donde presentó una
distribución casi simétrica con curtosis cercana a 3. En contraste,
<code>medincome</code> y <code>pctbachdeg25_over</code> muestran los estadísticos de
Anderson-Darling más altos (47.29 y 42.15, respectivamente), reflejando una
desviación más marcada de la normalidad, en línea con los altos
coeficientes de asimetría y curtosis identificados previamente para ambas
variables.</p>
<p>Dado que el supuesto de normalidad no se cumple para ninguna de las
variables involucradas, se procede a estimar la asociación mediante
coeficientes de correlación no paramétricos.</p>
<p>En primer lugar, se calcula el coeficiente de correlación de Spearman:</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="Análisis_estadístico.html#cb88-1" tabindex="-1"></a>resultados_spearman <span class="ot">&lt;-</span> <span class="fu">lapply</span>(variables_corr[<span class="sc">-</span><span class="dv">1</span>], <span class="cf">function</span>(v) {</span>
<span id="cb88-2"><a href="Análisis_estadístico.html#cb88-2" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(df[[v]], df<span class="sc">$</span>target_deathrate, <span class="at">method =</span> <span class="st">&quot;spearman&quot;</span>)</span>
<span id="cb88-3"><a href="Análisis_estadístico.html#cb88-3" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb88-4"><a href="Análisis_estadístico.html#cb88-4" tabindex="-1"></a>    <span class="at">variable =</span> v,</span>
<span id="cb88-5"><a href="Análisis_estadístico.html#cb88-5" tabindex="-1"></a>    <span class="at">correlacion =</span> <span class="fu">round</span>(test<span class="sc">$</span>estimate, <span class="dv">3</span>),</span>
<span id="cb88-6"><a href="Análisis_estadístico.html#cb88-6" tabindex="-1"></a>    <span class="at">p_value =</span> <span class="fu">round</span>(test<span class="sc">$</span>p.value, <span class="dv">4</span>)</span>
<span id="cb88-7"><a href="Análisis_estadístico.html#cb88-7" tabindex="-1"></a>  )</span>
<span id="cb88-8"><a href="Análisis_estadístico.html#cb88-8" tabindex="-1"></a>}) <span class="sc">%&gt;%</span> <span class="fu">bind_rows</span>()</span>
<span id="cb88-9"><a href="Análisis_estadístico.html#cb88-9" tabindex="-1"></a></span>
<span id="cb88-10"><a href="Análisis_estadístico.html#cb88-10" tabindex="-1"></a>resultados_spearman</span></code></pre></div>
<pre><code>##                     variable correlacion p_value
## rho...1            medincome      -0.463       0
## rho...2    pctbachdeg25_over      -0.502       0
## rho...3     coverage_balance      -0.430       0
## rho...4 pctunemployed16_over       0.403       0</code></pre>
<p>Posteriormente, se verifican los resultados mediante el coeficiente de
correlación de Kendall’s Tau, dado que la presencia de valores repetidos
(empates) en los datos impide calcular un p-valor exacto para Spearman:</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="Análisis_estadístico.html#cb90-1" tabindex="-1"></a>resultados_kendall <span class="ot">&lt;-</span> <span class="fu">lapply</span>(variables_corr[<span class="sc">-</span><span class="dv">1</span>], <span class="cf">function</span>(v) {</span>
<span id="cb90-2"><a href="Análisis_estadístico.html#cb90-2" tabindex="-1"></a>  test <span class="ot">&lt;-</span> <span class="fu">cor.test</span>(df[[v]], df<span class="sc">$</span>target_deathrate, <span class="at">method =</span> <span class="st">&quot;kendall&quot;</span>)</span>
<span id="cb90-3"><a href="Análisis_estadístico.html#cb90-3" tabindex="-1"></a>  <span class="fu">data.frame</span>(</span>
<span id="cb90-4"><a href="Análisis_estadístico.html#cb90-4" tabindex="-1"></a>    <span class="at">variable =</span> v,</span>
<span id="cb90-5"><a href="Análisis_estadístico.html#cb90-5" tabindex="-1"></a>    <span class="at">correlacion =</span> <span class="fu">round</span>(test<span class="sc">$</span>estimate, <span class="dv">3</span>),</span>
<span id="cb90-6"><a href="Análisis_estadístico.html#cb90-6" tabindex="-1"></a>    <span class="at">p_value =</span> <span class="fu">round</span>(test<span class="sc">$</span>p.value, <span class="dv">4</span>)</span>
<span id="cb90-7"><a href="Análisis_estadístico.html#cb90-7" tabindex="-1"></a>  )</span>
<span id="cb90-8"><a href="Análisis_estadístico.html#cb90-8" tabindex="-1"></a>}) <span class="sc">%&gt;%</span> <span class="fu">bind_rows</span>()</span>
<span id="cb90-9"><a href="Análisis_estadístico.html#cb90-9" tabindex="-1"></a></span>
<span id="cb90-10"><a href="Análisis_estadístico.html#cb90-10" tabindex="-1"></a>resultados_kendall</span></code></pre></div>
<pre><code>##                     variable correlacion p_value
## tau...1            medincome      -0.325       0
## tau...2    pctbachdeg25_over      -0.355       0
## tau...3     coverage_balance      -0.305       0
## tau...4 pctunemployed16_over       0.283       0</code></pre>
<p><code>pctbachdeg25_over</code> presenta la asociación más fuerte con <code>target_deathrate</code>
(ρ = -0.502, τ = -0.355), de signo negativo, lo que indica que a mayor
porcentaje de personas con título universitario, menor tiende a ser la
tasa de mortalidad por cáncer. Le sigue <code>medincome</code> (ρ = -0.463, τ = -0.325),
también con relación negativa, consistente con la idea de que un mayor
ingreso medio se asocia con menor mortalidad. <code>coverage_balance</code> muestra
una asociación negativa de magnitud similar (ρ = -0.430, τ = -0.305), lo
que sugiere que un mayor predominio de cobertura privada frente a la
pública se relaciona con tasas de mortalidad más bajas. Finalmente,
<code>pctunemployed16_over</code> es la única variable con asociación positiva
(ρ = 0.403, τ = 0.283), indicando que a mayor tasa de desempleo, mayor
tiende a ser la mortalidad por cáncer.</p>
<p>En todos los casos, los p-valores son menores a 0.001, por lo que las
cuatro asociaciones son estadísticamente significativas al 95% de
confianza, y ambos coeficientes coinciden tanto en el signo como en el
orden de fuerza de las variables, lo que respalda la consistencia de los
resultados. En términos de magnitud, todas las correlaciones se ubican en
un rango moderado (entre 0.3 y 0.5 en valor absoluto), lo cual confirma lo
observado en los diagramas de dispersión del EDA: cada variable por sí
sola guarda una relación real pero no lo suficientemente fuerte como para
explicar la totalidad de la variabilidad de <code>target_deathrate</code>, reforzando
la necesidad de un modelo de regresión múltiple que capture el efecto
conjunto de estas variables.</p>
</div>
<div id="objetivo-4.-contrastar-el-efecto-del-balance-de-cobertura-médica" class="section level2 hasAnchor" number="2.3">
<h2><span class="header-section-number">2.3</span> Objetivo #4. Contrastar el efecto del balance de cobertura médica<a href="Análisis_estadístico.html#objetivo-4.-contrastar-el-efecto-del-balance-de-cobertura-m%C3%A9dica" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><strong>Paso 1: Categorización de coverage_balance en 3 grupos (terciles)</strong>
Se optó por dividir <code>coverage_balance</code> en terciles (en lugar de utilizar
puntos de corte fijos o arbitrarios) porque este método garantiza que cada
grupo contenga aproximadamente el mismo número de observaciones (33.3% de
los datos cada uno), lo cual es preferible para un análisis de varianza, ya
que grupos con tamaños muestrales muy desbalanceados pueden afectar la
potencia estadística de la prueba y la validez del supuesto de
homogeneidad de varianzas. Además, al basarse en los percentiles reales de
la distribución de la variable (y no en umbrales predefinidos sin
fundamento estadístico, como 0 o 30), los terciles reflejan de forma más
fiel la estructura y variabilidad observada en los datos, evitando que la
elección subjetiva de los puntos de corte introduzca sesgos en la
comparación de grupos.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="Análisis_estadístico.html#cb92-1" tabindex="-1"></a>terciles <span class="ot">&lt;-</span> <span class="fu">quantile</span>(df<span class="sc">$</span>coverage_balance, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">1</span><span class="sc">/</span><span class="dv">3</span>, <span class="dv">2</span><span class="sc">/</span><span class="dv">3</span>))</span>
<span id="cb92-2"><a href="Análisis_estadístico.html#cb92-2" tabindex="-1"></a></span>
<span id="cb92-3"><a href="Análisis_estadístico.html#cb92-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb92-4"><a href="Análisis_estadístico.html#cb92-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria_cobertura =</span> <span class="fu">case_when</span>(</span>
<span id="cb92-5"><a href="Análisis_estadístico.html#cb92-5" tabindex="-1"></a>    coverage_balance <span class="sc">&lt;=</span> terciles[<span class="dv">1</span>] <span class="sc">~</span> <span class="st">&quot;Predominio público&quot;</span>,</span>
<span id="cb92-6"><a href="Análisis_estadístico.html#cb92-6" tabindex="-1"></a>    coverage_balance <span class="sc">&lt;=</span> terciles[<span class="dv">2</span>] <span class="sc">~</span> <span class="st">&quot;Balance intermedio&quot;</span>,</span>
<span id="cb92-7"><a href="Análisis_estadístico.html#cb92-7" tabindex="-1"></a>    <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;Predominio privado&quot;</span></span>
<span id="cb92-8"><a href="Análisis_estadístico.html#cb92-8" tabindex="-1"></a>  )) <span class="sc">%&gt;%</span> </span>
<span id="cb92-9"><a href="Análisis_estadístico.html#cb92-9" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">categoria_cobertura =</span> <span class="fu">factor</span>(categoria_cobertura, </span>
<span id="cb92-10"><a href="Análisis_estadístico.html#cb92-10" tabindex="-1"></a>         <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Predominio público&quot;</span>, <span class="st">&quot;Balance intermedio&quot;</span>, <span class="st">&quot;Predominio privado&quot;</span>)))</span>
<span id="cb92-11"><a href="Análisis_estadístico.html#cb92-11" tabindex="-1"></a></span>
<span id="cb92-12"><a href="Análisis_estadístico.html#cb92-12" tabindex="-1"></a><span class="fu">table</span>(df<span class="sc">$</span>categoria_cobertura)</span></code></pre></div>
<pre><code>## 
## Predominio público Balance intermedio Predominio privado 
##               1016               1020               1011</code></pre>
<p><strong>Paso 2: Resumen descriptivo de target_deathrate por grupo</strong></p>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="Análisis_estadístico.html#cb94-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb94-2"><a href="Análisis_estadístico.html#cb94-2" tabindex="-1"></a>  <span class="fu">group_by</span>(categoria_cobertura) <span class="sc">%&gt;%</span> </span>
<span id="cb94-3"><a href="Análisis_estadístico.html#cb94-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb94-4"><a href="Análisis_estadístico.html#cb94-4" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(target_deathrate),</span>
<span id="cb94-5"><a href="Análisis_estadístico.html#cb94-5" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(target_deathrate), </span>
<span id="cb94-6"><a href="Análisis_estadístico.html#cb94-6" tabindex="-1"></a>    <span class="at">d_est =</span> <span class="fu">sd</span>(target_deathrate),</span>
<span id="cb94-7"><a href="Análisis_estadístico.html#cb94-7" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(target_deathrate), </span>
<span id="cb94-8"><a href="Análisis_estadístico.html#cb94-8" tabindex="-1"></a>    <span class="at">RIC =</span> <span class="fu">IQR</span>(target_deathrate), </span>
<span id="cb94-9"><a href="Análisis_estadístico.html#cb94-9" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(target_deathrate, <span class="fl">0.25</span>), </span>
<span id="cb94-10"><a href="Análisis_estadístico.html#cb94-10" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(target_deathrate, <span class="fl">0.75</span>), </span>
<span id="cb94-11"><a href="Análisis_estadístico.html#cb94-11" tabindex="-1"></a>    <span class="at">min =</span> <span class="fu">min</span>(target_deathrate), </span>
<span id="cb94-12"><a href="Análisis_estadístico.html#cb94-12" tabindex="-1"></a>    <span class="at">max =</span> <span class="fu">max</span>(target_deathrate), </span>
<span id="cb94-13"><a href="Análisis_estadístico.html#cb94-13" tabindex="-1"></a>    <span class="at">curtosis =</span> <span class="fu">kurtosis</span>(target_deathrate), </span>
<span id="cb94-14"><a href="Análisis_estadístico.html#cb94-14" tabindex="-1"></a>    <span class="at">Coef_asim =</span> <span class="fu">skewness</span>(target_deathrate)</span>
<span id="cb94-15"><a href="Análisis_estadístico.html#cb94-15" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 3 × 12
##   categoria_cobertura     n media d_est mediana   RIC    Q1    Q3   min   max curtosis Coef_asim
##   &lt;fct&gt;               &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
## 1 Predominio público   1016  191.  29.9    193.  39.5  172.  211   66.3  292.     3.45   -0.0332
## 2 Balance intermedio   1020  180.  23.6    180.  27.1  166.  193. 102.   363.     7.11    0.395 
## 3 Predominio privado   1011  165.  22.7    165.  26.8  152.  179.  59.7  292.     4.82   -0.0589</code></pre>
<p>El resumen descriptivo de <code>target_deathrate</code> por categoría de balance de
cobertura muestra que la media de mortalidad disminuye a medida que
aumenta el predominio de la cobertura privada, pasando de 191.26 en
“Predominio público” a 179.66 en “Balance intermedio” y 164.99 en
“Predominio privado” —una diferencia de aproximadamente 26 muertes por
cada 100,000 habitantes entre los grupos extremos. Este mismo patrón se
replica en la mediana, lo que refuerza la consistencia de la tendencia.</p>
<p>Los tres grupos presentan tamaños muestrales muy similares (1016, 1020 y
1011 respectivamente), como era de esperarse al dividir la variable en
terciles. En cuanto a la dispersión, “Predominio público” muestra la mayor
variabilidad (DE = 29.89, RIC = 39.45), mientras que “Predominio privado”
es el más homogéneo (DE = 22.66, RIC = 26.80), sugiriendo que las regiones
con mayor dependencia de cobertura pública no solo presentan mortalidad
más alta en promedio, sino también más heterogénea.</p>
<p>Respecto a la forma de las distribuciones, “Balance intermedio” destaca
por una curtosis notablemente más alta (7.11) que los otros dos grupos
(3.45 y 4.82), lo que indica una concentración de datos más marcada
alrededor de su media junto con colas más pesadas —consistente con su
valor máximo considerablemente más alto (362.8) respecto a los otros dos
grupos. En cuanto a la asimetría, los tres grupos muestran coeficientes
cercanos a cero (entre -0.06 y 0.39), indicando distribuciones
razonablemente simétricas dentro de cada categoría, con “Balance
intermedio” presentando el sesgo positivo más notorio.</p>
<p><strong>Paso 3: Visualización - boxplot por grupo</strong></p>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="Análisis_estadístico.html#cb96-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb96-2"><a href="Análisis_estadístico.html#cb96-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> categoria_cobertura, <span class="at">y =</span> target_deathrate)) <span class="sc">+</span></span>
<span id="cb96-3"><a href="Análisis_estadístico.html#cb96-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#8ecae6&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#023047&quot;</span>, </span>
<span id="cb96-4"><a href="Análisis_estadístico.html#cb96-4" tabindex="-1"></a>  <span class="at">outlier.color =</span> <span class="st">&quot;#e63946&quot;</span>)<span class="sc">+</span></span>
<span id="cb96-5"><a href="Análisis_estadístico.html#cb96-5" tabindex="-1"></a>    <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&#39;point&#39;</span>, <span class="at">shape =</span> <span class="dv">20</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&#39;#023047&#39;</span>) <span class="sc">+</span></span>
<span id="cb96-6"><a href="Análisis_estadístico.html#cb96-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Tasa de mortalidad por categoría de balance de cobertura&quot;</span>,</span>
<span id="cb96-7"><a href="Análisis_estadístico.html#cb96-7" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">&quot;Categoría de cobertura&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Tasa de mortalidad (por 100,000 hab.)&quot;</span>) <span class="sc">+</span></span>
<span id="cb96-8"><a href="Análisis_estadístico.html#cb96-8" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb96-9"><a href="Análisis_estadístico.html#cb96-9" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>)</span></code></pre></div>
<p><img src="bookdown-demo_files/figure-html/boxplot-1.png" alt="" width="672" /></p>
<p>El diagrama de cajas y bigotes muestra un patrón claro entre las tres
categorías: a medida que aumenta el predominio de la cobertura privada
sobre la pública, la tasa de mortalidad por cáncer tiende a disminuir. El
grupo de “Predominio público” presenta la mediana más alta (cercana a 190),
seguido por “Balance intermedio” (mediana alrededor de 180), y finalmente
“Predominio privado” con la mediana más baja (cercana a 165).</p>
<p>Asimismo, se observa que la dispersión de los datos disminuye ligeramente
a medida que aumenta el predominio de la cobertura privada, siendo el
grupo de “Predominio público” el que presenta el rango intercuartílico más
amplio. Los tres grupos muestran una cantidad considerable de valores
atípicos en ambos extremos, particularmente en la cola superior.</p>
<p>En conjunto, estas diferencias visuales entre las medianas de los tres
grupos sugieren que el tipo de cobertura médica predominante podría estar
asociado con diferencias en la tasa de mortalidad, lo cual será contrastado
formalmente mediante la prueba de análisis de varianza (o su alternativa
no paramétrica, según los supuestos evaluados).</p>
<p><strong>Paso 4: Verificar supuestos de ANOVA</strong></p>
<p>Se prueba la normalidad de <code>target_deathrate</code> dentro de cada grupo con la prueba Shapiro-Wilk y verificando con la prueba Anderson-Darling</p>
<div class="sourceCode" id="cb97"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb97-1"><a href="Análisis_estadístico.html#cb97-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb97-2"><a href="Análisis_estadístico.html#cb97-2" tabindex="-1"></a>  <span class="fu">group_by</span>(categoria_cobertura) <span class="sc">%&gt;%</span> </span>
<span id="cb97-3"><a href="Análisis_estadístico.html#cb97-3" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb97-4"><a href="Análisis_estadístico.html#cb97-4" tabindex="-1"></a>    <span class="at">shapiro_W =</span> <span class="fu">round</span>(<span class="fu">shapiro.test</span>(target_deathrate)<span class="sc">$</span>statistic, <span class="dv">4</span>),</span>
<span id="cb97-5"><a href="Análisis_estadístico.html#cb97-5" tabindex="-1"></a>    <span class="at">shapiro_p =</span> <span class="fu">round</span>(<span class="fu">shapiro.test</span>(target_deathrate)<span class="sc">$</span>p.value, <span class="dv">4</span>),</span>
<span id="cb97-6"><a href="Análisis_estadístico.html#cb97-6" tabindex="-1"></a>    <span class="at">ad_stat =</span> <span class="fu">round</span>(<span class="fu">ad.test</span>(target_deathrate)<span class="sc">$</span>statistic, <span class="dv">4</span>),</span>
<span id="cb97-7"><a href="Análisis_estadístico.html#cb97-7" tabindex="-1"></a>    <span class="at">ad_p =</span> <span class="fu">round</span>(<span class="fu">ad.test</span>(target_deathrate)<span class="sc">$</span>p.value, <span class="dv">4</span>)</span>
<span id="cb97-8"><a href="Análisis_estadístico.html#cb97-8" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 3 × 5
##   categoria_cobertura shapiro_W shapiro_p ad_stat   ad_p
##   &lt;fct&gt;                   &lt;dbl&gt;     &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;
## 1 Predominio público      0.996    0.0092    1.17 0.0047
## 2 Balance intermedio      0.971    0         3.26 0     
## 3 Predominio privado      0.986    0         1.93 0.0001</code></pre>
<p>Los resultados muestran que se rechaza la hipótesis de normalidad en los
tres grupos (p &lt; 0.05 en todos los casos, tanto para Shapiro-Wilk como para
Anderson-Darling). El grupo “Predominio público” presenta el p-valor más
alto en ambas pruebas (Shapiro: p = 0.0092; Anderson-Darling: p = 0.0047),
indicando que, aunque técnicamente no cumple normalidad, es el que más se
aproxima a ella entre los tres. En contraste, “Balance intermedio” muestra
el rechazo más contundente (p &lt; 0.001 en ambas pruebas), consistente con
la elevada curtosis (7.11) identificada previamente en su resumen
descriptivo, producto del valor atípico presente en ese grupo.</p>
<p>Dado que el supuesto de normalidad no se cumple en ninguno de los tres
grupos, se opta por la alternativa no paramétrica de ANOVA, es decir, prueba de Kruskal-Wallis.</p>
<p><strong>Paso 5: Implementar el modelo pertinente</strong></p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="Análisis_estadístico.html#cb99-1" tabindex="-1"></a><span class="fu">kruskal.test</span>(target_deathrate <span class="sc">~</span> categoria_cobertura, <span class="at">data =</span> df)</span></code></pre></div>
<pre><code>## 
##  Kruskal-Wallis rank sum test
## 
## data:  target_deathrate by categoria_cobertura
## Kruskal-Wallis chi-squared = 491.08, df = 2, p-value &lt; 2.2e-16</code></pre>
<p>Dado que no se cumple el supuesto de normalidad en ninguno de los tres
grupos, se aplica la prueba no paramétrica de Kruskal-Wallis como
alternativa al ANOVA clásico. El resultado obtenido (χ² = 491.08, gl = 2,
p &lt; 2.2e-16) indica que se rechaza la hipótesis nula de igualdad de
distribuciones entre los tres grupos, con un nivel de significancia muy
por debajo de 0.001. Esto confirma, con alta confianza estadística, que
existen diferencias significativas en la tasa de mortalidad por cáncer
entre las categorías de balance de cobertura médica (predominio público,
balance intermedio y predominio privado).</p>
<p>Este resultado es consistente con el patrón observado en el análisis
descriptivo, donde las medias y medianas de <code>target_deathrate</code> mostraban
una disminución progresiva desde el grupo de predominio público hacia el
de predominio privado. Para determinar específicamente entre qué pares de
grupos existen estas diferencias, se procede a realizar un análisis
post-hoc mediante la prueba de Dunn.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="Análisis_estadístico.html#cb101-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb101-2"><a href="Análisis_estadístico.html#cb101-2" tabindex="-1"></a>  <span class="fu">dunn_test</span>(target_deathrate <span class="sc">~</span> categoria_cobertura, <span class="at">p.adjust.method =</span> <span class="st">&quot;bonferroni&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 9
##   .y.              group1             group2       n1    n2 statistic         p     p.adj p.adj.signif
## * &lt;chr&gt;            &lt;chr&gt;              &lt;chr&gt;     &lt;int&gt; &lt;int&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt; &lt;chr&gt;       
## 1 target_deathrate Predominio público Balance …  1016  1020     -8.90 5.64e- 19 1.69e- 18 ****        
## 2 target_deathrate Predominio público Predomin…  1016  1011    -22.0  1.63e-107 4.89e-107 ****        
## 3 target_deathrate Balance intermedio Predomin…  1020  1011    -13.2  1.50e- 39 4.51e- 39 ****</code></pre>
<p>El análisis post-hoc mediante la prueba de Dunn confirma que las
diferencias son estadísticamente significativas entre <strong>todos</strong> los pares
de grupos comparados (p.adj &lt; 0.001 en los tres casos, con el máximo nivel
de significancia posible, indicado por ****).</p>
<p>La diferencia más marcada se observa entre “Predominio público” y
“Predominio privado” (estadístico = -22.03, p.adj ≈ 4.89e-107), lo cual es
coherente con que estos representan los extremos opuestos del espectro de
cobertura médica. Le sigue la comparación entre “Balance intermedio” y
“Predominio privado” (estadístico = -13.16, p.adj ≈ 4.51e-39), y finalmente
la diferencia menos pronunciada, aunque igualmente significativa, entre
“Predominio público” y “Balance intermedio” (estadístico = -8.90,
p.adj ≈ 1.69e-18).</p>
<p>En conjunto, estos resultados confirman que la tasa de mortalidad por
cáncer difiere significativamente entre las tres categorías de balance de
cobertura médica, y que dicha diferencia sigue un patrón gradual y
consistente: a mayor predominio de cobertura privada, menor es la tasa de
mortalidad, validando estadísticamente la tendencia observada en el
análisis descriptivo y gráfico previo.</p>



</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="metodología.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referencias.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/04-Analisis_estadistico.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
